version: '3.8'

services:
  web:
    image: ${DOCKER_IMAGE:-justincnn/excel-translator:latest}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./.env:/app/.env
      - ./api_config.json:/app/api_config.json
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - TRANSLATION_API_URL=${TRANSLATION_API_URL}
      - TRANSLATION_API_KEY=${TRANSLATION_API_KEY}
      - TRANSLATION_PROMPT=${TRANSLATION_PROMPT}
      - MAX_CONTENT_LENGTH=${MAX_CONTENT_LENGTH:-16777216}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key}
      - DEBUG=${DEBUG:-false}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - USE_HTTPS=${USE_HTTPS:-false}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 