name: Docker Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          server: https://index.docker.io/v1/

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            justincnn/excel-translator:latest
            justincnn/excel-translator:${{ github.sha }}
          cache-from: type=registry,ref=justincnn/excel-translator:buildcache
          cache-to: type=registry,ref=justincnn/excel-translator:buildcache,mode=max
          build-args: |
            BUILDKIT_INLINE_CACHE=1 